---
# tasks file for ansible-yubikey-mac

- name: Ensure gnupg2 & pinentry-mac are installed
  homebrew:
    name: "{{ item.name }}"
    state: installed
  loop:
    - gnupg2
    - pinentry-mac

  - blockinfile:
      path: ~/.gnupg/gpg-agent.conf
      create: yes
      block: |
        pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
        enable-ssh-support
        write-env-file
        use-standard-socket
        default-cache-ttl 600
        max-cache-ttl 7200

  - blockinfile:
      path: ~/.zprofile
      create: yes
      block: |
        export GPG_TTY="$(tty)"
        export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
        gpgconf --launch gpg-agent
        zsh