---
# tasks file for ansible-yubikey-mac

- name: Ensure gnupg2 & pinentry-mac are installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - gnupg2
    - pinentry-mac

- name: Create directory ~/.gnupg if it does not exist
  become: true
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700

- name: create ~/.gnupg/gpg-agent.conf
  become: true
  blockinfile:
    path: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    block: |
      pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
      enable-ssh-support
      write-env-file
      use-standard-socket
      default-cache-ttl 600
      max-cache-ttl 7200

- name: create ~/.zprofile
  become: true
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    block: |
      export GPG_TTY="$(tty)"
      export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
      gpgconf --launch gpg-agent
      zsh
