---
# tasks file for ansible-yubikey-mac

- name: Ensure gnupg2 & pinentry-mac are installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - gnupg2
    - pinentry-mac
  when: ansible_distribution == "MacOSX"

- name: Ensure gnupg, pcsclite, ccid, hopenpgp-tools & yubikey-personalization are installed
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - gnupg
    - pcsclite
    - ccid
    - hopenpgp-tools
    - yubikey-personalization
  when: ansible_distribution == 'Archlinux'

- name: Create directory ~/.gnupg if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700

- name: create ~/.gnupg/gpg-agent.conf
  template:
    src: "gpg-agent.conf.j2"
    dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
    owner: "{{ ansible_env.USER }}"
    mode: 0600
